name: Update Changelog

on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only run when the PR was merged. The 'closed' state also includes closed but not merged PRs
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: ${{ secrets.DB_FE_GITHUB_APP_ID }}
          installation_id: ${{ secrets.DB_FE_GITHUB_APP_INSTALLATION_ID }}
          private_key: ${{ secrets.DB_FE_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          # We want to update our changelog on main
          ref: 'main'
          fetch-depth: 0
          token: ${{ steps.get_installation_token.outputs.token }}

      - name: Setup credentials to access Grafana private repositories
        run: git config --global url.https://${{ steps.get_installation_token.outputs.token }}@github.com/.insteadOf https://github.com/

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install utilities
        run: sudo apt-get install jq

      - name: Get PR information
        id: pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        run: |
          PR_LINE=$(node .github/workflows/scripts/get-changelog-line.js)
          sed -i "/## 1.0.0 (Unreleased)/ a $PR_LINE" CHANGELOG.md
          git add CHANGELOG.md
        env:
          PR_DATA: ${{ steps.pr.outputs.data }}

      - name: Commit changelog
        id: commit-changelog
        uses: grafana/github-api-commit-action@v0
        with:
          token: ${{ steps.get_installation_token.outputs.token }}
          commit-message: 'chore(changelog): update changelog [BOT]'
