version: '3.0'

services:
  grafana: &grafana
    container_name: '{{ pluginId }}'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-{{~grafanaImage~}} }
        grafana_version: ${GRAFANA_VERSION:-{{~grafanaVersion~}} }
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/{{ pluginId }}
      - ./provisioning:/etc/grafana/provisioning

  e2e:
    <<: *grafana
    profiles:
      - e2e
    volumes:
      - ./src/test/msw:/usr/share/grafana/public/msw
      - ./dist:/var/lib/grafana/plugins/{{ pluginId }}
      - ./e2e/provisioning:/etc/grafana/provisioning